

CREATE TABLE KOLOFORTUNY_KATEGORIE (
	ID INTEGER NOT NULL,
	NAME VARCHAR(20),
	CONSTRAINT KOLOFORTUNY_KATEGORIE_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_KATEGORIE_PK ON KOLOFORTUNY_KATEGORIE (ID);

CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Polityka (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Polityka_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Polityka_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Muzyka (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Muzyka_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Muzyka_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Biologia (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Biologia_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Biologia_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Geografia (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Geografia_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Geografia_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Chemia (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Chemia_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Chemia_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Fizyka (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Fizyka_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Fizyka_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Religie (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Religie_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Religie_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Informatyka (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Informatyka_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Informatyka_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Anatomia (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Anatomia_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Anatomia_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Sport (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Sport_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Sport_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);


CREATE INDEX SYS_IDX_KOLOFORTUNY_Polityka_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Polityka (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Polityka_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Polityka (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Muzyka_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Muzyka (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Muzyka_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Muzyka (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Biologia_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Biologia (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Biologia_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Biologia (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Geografia_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Geografia (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Geografia_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Geografia (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Chemia_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Chemia (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Chemia_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Chemia (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Fizyka_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Fizyka (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Fizyka_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Fizyka (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Religie_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Religie (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Religie_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Religie (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Informatyka_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Informatyka (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Informatyka_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Informatyka (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Anatomia_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Anatomia (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Anatomia_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Anatomia (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Sport_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Sport (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Sport_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Sport (ID);