
CREATE TABLE KOLOFORTUNY_KATEGORIE (
	ID INTEGER NOT NULL,
	NAME VARCHAR(20),
	CONSTRAINT KOLOFORTUNY_KATEGORIE_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_KATEGORIE_PK ON KOLOFORTUNY_KATEGORIE (ID);

CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Polityka (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Polityka_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Polityka_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Muzyka (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Muzyka_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Muzyka_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Biologia (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Biologia_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Biologia_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Geografia (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Geografia_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Geografia_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Chemia (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Chemia_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Chemia_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Fizyka (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Fizyka_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Fizyka_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Religie (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Religie_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Religie_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Informatyka (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Informatyka_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Informatyka_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Anatomia (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Anatomia_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Anatomia_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_Sport (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_Sport_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_Sport_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);


CREATE INDEX SYS_IDX_KOLOFORTUNY_Polityka_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Polityka (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Polityka_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Polityka (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Muzyka_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Muzyka (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Muzyka_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Muzyka (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Biologia_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Biologia (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Biologia_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Biologia (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Geografia_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Geografia (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Geografia_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Geografia (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Chemia_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Chemia (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Chemia_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Chemia (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Fizyka_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Fizyka (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Fizyka_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Fizyka (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Religie_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Religie (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Religie_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Religie (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Informatyka_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Informatyka (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Informatyka_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Informatyka (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Anatomia_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Anatomia (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Anatomia_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Anatomia (ID);
CREATE INDEX SYS_IDX_KOLOFORTUNY_Sport_FK ON PUBLIC.PUBLIC.KOLOFORTUNY_Sport (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_Sport_PK ON PUBLIC.PUBLIC.KOLOFORTUNY_Sport (ID);

INSERT INTO PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE (ID,NAME) VALUES
	 (1,'Polityka'),
	 (2,'Muzyka'),
	 (3,'Biologia'),
	 (4,'Geografia'),
	 (5,'Chemia'),
	 (6,'Fizyka'),
	 (7,'Religie'),
	 (8,'Informatyka'),
	 (9,'Anatomia'),
	 (10,'Sport');

	 INSERT INTO PUBLIC.PUBLIC.KOLOFORTUNY_POLITYKA (ID,CATEGORY_ID,WORD) VALUES
     	 (1,1,'Sejm'),
     	 (2,1,'Senat'),
     	 (3,1,'Konstytucja'),
     	 (4,1,'Ministerstwo Finansów'),
     	 (5,1,'Wybory '),
     	 (6,1,'Prezydent'),
     	 (7,1,'Premier'),
     	 (8,1,'Koalicja'),
     	 (9,1,'Partia'),
     	 (10,1,'Immunitet');

     	 INSERT INTO PUBLIC.PUBLIC.KOLOFORTUNY_Muzyka (ID,CATEGORY_ID,WORD) VALUES
     	 (1,2,'Opera'),
     	 (2,2,'Wiolonczela'),
     	 (3,2,'Solista'),
     	 (4,2,'Festiwal muzyczny'),
     	 (5,2,'Koncert'),
     	 (6,2,'Zespół muzyczny'),
     	 (7,2,'Fortepian'),
     	 (8,2,'Gitara akustyczna'),
     	 (9,2,'Szanty'),
     	 (10,2,'Hymn Państwowy');

     	 INSERT INTO PUBLIC.PUBLIC.KOLOFORTUNY_Biologia (ID,CATEGORY_ID,WORD) VALUES
     	 (1,3,'Roślin'),
     	 (2,3,'Ssaki'),
     	 (3,3,'Pantofelek'),
     	 (4,3,'Ptaki'),
     	 (5,3,'Ryby'),
     	 (6,3,'Fotosynteza'),
     	 (7,3,'Naczelne'),
     	 (8,3,'Dinozaury'),
     	 (9,3,'Płaz'),
     	 (10,3,'Krokodyl');
     	 INSERT INTO PUBLIC.PUBLIC.KOLOFORTUNY_Geografia (ID,CATEGORY_ID,WORD) VALUES
     	 (1,4,'Rzeka'),
     	 (2,4,'Kontynent'),
     	 (3,4,'Płyta tektoniczna'),
     	 (4,4,'Oceany'),
     	 (5,4,'Góry'),
     	 (6,4,'Biegun Północny'),
     	 (7,4,'Afryka'),
     	 (8,4,'Równik'),
     	 (9,4,'Wody głębinowe'),
     	 (10,4,'Puszcza Amazońska');
     	 INSERT INTO PUBLIC.PUBLIC.KOLOFORTUNY_Chemia (ID,CATEGORY_ID,WORD) VALUES
     	 (1,5,'Pierwiastek'),
     	 (2,5,'Tablica Mendelejewa'),
     	 (3,5,'Reakcja chemiczna'),
     	 (4,5,'Kwas'),
     	 (5,5,'Metale'),
     	 (6,5,'Etanol'),
     	 (7,5,'Woda utleniona'),
     	 (8,5,'Doświadczenie chemiczne'),
     	 (9,5,'Amony'),
     	 (10,5,'Radioaktywność');
     	 INSERT INTO PUBLIC.PUBLIC.KOLOFORTUNY_fizyka (ID,CATEGORY_ID,WORD) VALUES
     	 (1,6,'Grawitacja'),
     	 (2,6,'Termodynamika'),
     	 (3,6,'Amplituda'),
     	 (4,6,'Fale radiowe'),
     	 (5,6,'Pierwsza zasada dynamiki'),
     	 (6,6,'Prąd elektryczny'),
     	 (7,6,'Ruch jednostajnie przyśpieszony'),
     	 (8,6,'Rezonans magnetyczny'),
     	 (9,6,'Teoria względności'),
     	 (10,6,'Woltomierz');
     	 INSERT INTO PUBLIC.PUBLIC.KOLOFORTUNY_Religie (ID,CATEGORY_ID,WORD) VALUES
     	 (1,7,'Hinduizm'),
     	 (2,7,'Chrześcijaństwo'),
     	 (3,7,'Synagoga'),
     	 (4,7,'Teologia'),
     	 (5,7,'Kult'),
     	 (6,7,'Wiara'),
     	 (7,7,'Chrzest'),
     	 (8,7,'Oświecenie'),
     	 (9,7,'Koran'),
     	 (10,7,'Biblia');
     	 INSERT INTO PUBLIC.PUBLIC.KOLOFORTUNY_Informatyka (ID,CATEGORY_ID,WORD) VALUES
     	 (1,8,'Baza danych'),
     	 (2,8,'Internet'),
     	 (3,8,'Serwerownia'),
     	 (4,8,'Języki programowania'),
     	 (5,8,'Wymagania biznesowe'),
     	 (6,8,'Aplikacja webowa'),
     	 (7,8,'Weblogic'),
     	 (8,8,'Naprawa błędów aplikacji'),
     	 (9,8,'Gry komputerowe'),
     	 (10,8,'Połączenie sieciowe');
     	 INSERT INTO PUBLIC.PUBLIC.KOLOFORTUNY_Anatomia (ID,CATEGORY_ID,WORD) VALUES
     	 (1,9,'Układ krążenia'),
     	 (2,9,'Kościec'),
     	 (3,9,'Tętnice'),
     	 (4,9,'Jelito'),
     	 (5,9,'Mózg'),
     	 (6,9,'Układ oddechowy'),
     	 (7,9,'Gałka oczna'),
     	 (8,9,'Trąbka słuchowa'),
     	 (9,9,'Rdzeń kręgowy'),
     	 (10,9,'Nerki');
     	 INSERT INTO PUBLIC.PUBLIC.KOLOFORTUNY_Sport (ID,CATEGORY_ID,WORD) VALUES
     	 (1,10,'Olimpiada'),
     	 (2,10,'Trener'),
     	 (3,10,'Zawodnik'),
     	 (4,10,'Mecz'),
     	 (5,10,'Gimnastyka artystyczna'),
     	 (6,10,'Łyżwiarstwo'),
     	 (7,10,'Skoki narciarskie'),
     	 (8,10,'Gra zespołowa'),
     	 (9,10,'Zawody'),
     	 (10,10,'Rower'),
     	 (11,10,'Nurkowanie');