

CREATE TABLE KOLOFORTUNY_KATEGORIE (
	ID INTEGER NOT NULL,
	NAME VARCHAR(20),
	CONSTRAINT KOLOFORTUNY_KATEGORIE_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_KATEGORIE_PK_10228 ON KOLOFORTUNY_KATEGORIE (ID);

CREATE TABLE PUBLIC.PUBLIC.KOLOFORTUNY_TABELASLOW (
	ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER,
	WORD VARCHAR(50),
	CONSTRAINT KOLOFORTUNY_TABELASLOW_PK PRIMARY KEY (ID),
	CONSTRAINT KOLOFORTUNY_TABELASLOW_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.PUBLIC.KOLOFORTUNY_KATEGORIE(ID)
);
CREATE INDEX SYS_IDX_KOLOFORTUNY_TABELASLOW_FK_10298 ON PUBLIC.PUBLIC.KOLOFORTUNY_TABELASLOW (CATEGORY_ID);
CREATE UNIQUE INDEX SYS_IDX_KOLOFORTUNY_TABELASLOW_PK_10189 ON PUBLIC.PUBLIC.KOLOFORTUNY_TABELASLOW (ID);
